### ISSUE TITLE
Creating and Inserting Dom Nodes Lab

### ISSUE THREAD

**Issue by evareitzel** [learn-co-curriculum/phase-0-the-dom-modifying-elements-lab#17]
### Canvas Link

https://learning.flatironschool.com/courses/5290/assignments/165378?module_item_id=356970

### Concern

Typo -

Let's append element to body to start:

document.body.append(element);
Now if you look at the Elements tab, you'll see our new (empty) <div> nested inside the body

### Suggested Changes

//// Should say: 
document.body.append("div");

**Comment by lizbur10** [comment]
Hi @evareitzel! `element` is a variable that was created a little earlier in the lesson that contains the `div`. I have added a sentence to make that clearer.

Thanks for contributing to the Flatiron School curriculum! 💙
