### ISSUE TITLE
methods used without intro/explanation

### ISSUE THREAD

**Issue by dandanthemanman** [learn-co-curriculum/phase-0-the-dom-modifying-elements-lab#9]
### Canvas Link

https://learning.flatironschool.com/courses/5470/assignments/168067?module_item_id=363234

### Concern

lines 64-67 used methods textContent and toString. These haven't yet been introduced

**Comment by professor-ben** [comment]
Thanks for letting us know! This has been reordered in the newest version of prework, but toString had not yet been introduced in your version. We have updated the lab to address this issue. This may not show up in Canvas just yet, but it will be there for future students. We appreciate your feedback!
